name: workflow-dev.yml

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      service_name:
        description: "Name of the service to deploy"
        required: true
        type: string
        default: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build image locally
        run: |
          SERVICE_NAME=${{ inputs.service_name || github.event.repository.name }}
          docker build -t $SERVICE_NAME:latest .

  deploy_local:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for docker-compose file
        run: |
          if [ ! -f docker-compose.yaml ]; then
            echo "Error: docker-compose.yaml not found"
            exit 1
          fi

      - name: Deploy local stack
        run: |
          SERVICE_NAME=${{ inputs.service_name || github.event.repository.name }}
          docker stack deploy -c docker-compose.yaml $SERVICE_NAME || { echo "Deployment failed"; exit 1; }