name: workflow-dev.yml

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      service_name:
        description: "Name of the service to deploy"
        required: true
        type: string
        default: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Build image with unique tag
        run: |
          SERVICE_NAME=${{ inputs.service_name || github.event.repository.name }}
          IMAGE_TAG=${GITHUB_SHA::8}
          IMAGE_NAME="$SERVICE_NAME:$IMAGE_TAG"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          docker build -t $IMAGE_NAME .
          docker image prune -f

  deploy_local:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for docker-compose file
        run: |
          if [ ! -f docker-compose.yaml ]; then
            echo "Error: docker-compose.yaml not found"
            exit 1
          fi

      - name: Deploy stack with dynamic image tag
        run: |
          SERVICE_NAME=${{ inputs.service_name || github.event.repository.name }}
          IMAGE_NAME=${{ env.IMAGE_NAME }}
          
          # Substitute IMAGE_NAME into docker-compose before deploying
          env IMAGE_NAME=$IMAGE_NAME docker stack deploy \
            -c <(envsubst < docker-compose.yaml) \
            $SERVICE_NAME --with-registry-auth --resolve-image never

  cleanup:
    needs: deploy_local
    runs-on: self-hosted
    steps:
      - name: Cleanup dangling images
        run: docker image prune -f
